language: objective-c
osx_image: xcode7
xcode_project: blank-ios-app.xcodeproj
xcode_scheme: blank-ios-app
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master